# Generated by Django 4.2 on 2023-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_timestampmodel_remove_task_id_task_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestampmodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timestampmodel',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
